# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
services:
  spark-iceberg:
    image: tabulario/spark-iceberg
    container_name: spark-iceberg
    build: ./spark
    networks:
      datalake_network:
    depends_on:
      - rest
      - minio
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
      - ./data:/opt/spark/data
      - ./spark/apps:/opt/spark/apps
      - ./spark/spark-logs:/home/iceberg/spark-events
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=ap-southeast-1
    command: >
      /bin/bash -c "
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      --host spark-iceberg --port 7077 --webui-port 8080 &
      jupyter notebook --notebook-dir=/home/iceberg/notebooks
      --ip=0.0.0.0 --port=8888 --no-browser --allow-root
      --NotebookApp.token=${JUPYTER_TOKEN}
      --NotebookApp.password=${JUPYTER_PASSWORD}"
    ports:
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 10001:10001
      - 18080:18080

  spark-worker:
    image: tabulario/spark-iceberg
    container_name: spark-worker
    networks:
      datalake_network:
    depends_on:
      - spark-iceberg
    environment:
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-iceberg:7077
      --cores 2
      --memory 2G
      --webui-port 8081
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./data:/opt/spark/data
      - ./spark/apps:/opt/spark/apps
      - ./spark/spark-logs:/home/iceberg/spark-events
    ports:
      - 8081:8081
  rest:
    image: apache/iceberg-rest-fixture
    container_name: iceberg-rest
    networks:
      datalake_network:
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      datalake_network:
        aliases:
          - warehouse.minio
    volumes:
      - ./storage/minio-data:/data
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]

  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      datalake_network:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc anonymous set public minio/warehouse;
      tail -f /dev/null
      "
networks:
  datalake_network:
